### PR TITLE
polkascan

### PR DESCRIPTION
**Pull request by ayushsingh82**
Pushing my final complete project

### CODE REVIEW

**Comment by papermoonzhou** [comment]
rebase and don't change other projects.

**Comment by ayushsingh82** [comment]
> rebase and don't change other projects.

I guess there is no conflict it can directly be merged

**Comment by papermoonzhou** [comment]
It is not about the conflict. you PR changes source files in other project folder. pls check the Files changed

**Comment by ayushsingh82** [comment]
> It is not about the conflict. you PR changes source files in other project folder. pls check the Files changed

I have done the rebase please merge

**Comment by papermoonzhou** [comment]
image

**Comment by papermoonzhou** [comment]
check the changed files. just update files in your project folder

**Comment by ayushsingh82** [comment]
> check the changed files. just update files in your project folder

I haven't changed anything in others folder do u know any command to fix it

**Comment by papermoonzhou** [comment]
close it, and create a new PR. just copy your project folder to new one.

**Comment by ayushsingh82** [comment]
> close it, and create a new PR. just copy your project folder to new one.

created a new pull request #217

**Comment by papermoonzhou** [comment]
close it. new commit is #217

**Pull request closed without merging**
