### PR TITLE
polkascan

### PR DESCRIPTION
**Pull request by ayushsingh82**
Pushing my project

### CODE REVIEW

**Comment by papermoonzhou** [comment]
image

**Comment by ayushsingh82** [comment]
> image




sir I dont know whats happening  , any other way to resolve this

**Comment by papermoonzhou** [comment]
just merge from oneblockplus main to your branch. fix the conflict if there is any

**Comment by ayushsingh82** [comment]
> just merge from oneblockplus main to your branch. fix the conflict if there is any

Please check now sir

**Comment by papermoonzhou** [comment]
doesn't work. seems you have deleted some files in your local. you can copy these files from oneblockplus main, then commit.

**Comment by ayushsingh82** [comment]
> doesn't work. seems you have deleted some files in your local. you can copy these files from oneblockplus main, then commit.

made changes in my local check now sir

**Pull request closed without merging**
